name: Latest blog posts from nd-cyber.com

on:
  schedule:
    - cron: "11 6 * * *"  # (staggered)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts from nd-cyber.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://nd-cyber.com/feed"
          max_post_count: 5
