name: Latest DarkReading.com news

on:
  schedule:
    - cron: "20 0 * * *"   # daily at 00:20 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-darkreading:
    name: Update this repo's README with today latest news from DarkReading.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "DARKREADING"
          max_post_count: 8
          feed_list: "https://www.darkreading.com/rss.xml"
