name: Latest The Hacker News

on:
  schedule:
    - cron: "20 0 * * *"  # daily at 00:20 UTC (staggered)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-thn:
    name: Update this repo's README with the latest items from The Hacker News
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "THEHACKERNEWS"
          feed_list: "https://thehackernews.com/feeds/posts/default"
          max_post_count: 10
