name: Latest YouTube Videos

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVsmmOPP9L42oTOlpYtojGQ"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          max_post_count: 5
          template: |
            <tr>
              <td width="1000" valign="top">
                <a href="$url">
                  <img width="100" src="https://img.youtube.com/vi/$videoId/hqdefault.jpg" />
                </a>
              </td>
              <td valign="middle">
                <a href="$url">$title</a>
              </td>
            </tr>
